Br-13-basis-annotation-processor
DimaYakovenko/breskul-bring-project pull request #21
Opened 2021-10-29 10:13 UTC by MishaBeheka

Created begin version of annotations scanner and process bean creation.

2021-10-30 10:16 UTC, MrFim commented on src/main/java/com/bring/library/App.java
> +package com.bring.library;
I would use Spring approach and rename `bring.library` to `bringframework`

2021-10-30 10:19 UTC, MrFim commented on src/main/java/com/bring/library/annotation/Autowired.java
> +public @interface Autowired {
1. Target should be not only field
2. IMO this annotation is out of scope of your task
3. We agreed that we would use different name for our annotations

2021-10-30 10:20 UTC, MrFim commented on src/main/java/com/bring/library/annotation/Component.java
> +public @interface Component {
IMO this is out of scope of your task

2021-10-30 10:20 UTC, MrFim commented on src/main/java/com/bring/library/annotation/Controller.java
> +public @interface Controller {
IMO this annotation is out of scope of your task

2021-10-30 10:22 UTC, MrFim commented on src/main/java/com/bring/library/annotation/Dao.java
> +public @interface Dao {
1. IMO this annotation is out of scope of your task
2. Is this annotation name is your version of `@Repository` annotation?

2021-10-30 10:22 UTC, MrFim commented on src/main/java/com/bring/library/annotation/Service.java
> +public @interface Service {
IMO this annotation is out of scope of your task

2021-10-30 10:26 UTC, MrFim commented on src/main/java/com/bring/library/exception/ClassHasMoreOneInterfacesException.java
> +    public ClassHasMoreOneInterfacesException(String message) {
I wouldn't create an exception for each possible case, because exception message will describe the problem. I would group them and use more suitable, for example: `BoboCreationException`, `ScanPackageException`

2021-10-30 10:29 UTC, MrFim commented on src/main/java/com/bring/library/exception/InvalidFileNameException.java
> +public class InvalidFileNameException extends RuntimeException {
for me instead of this exception, we can use `IllegalArgumentException`

2021-10-30 10:42 UTC, MrFim commented on src/main/java/com/bring/library/service/processor/impl/PackageScanner.java
> +    private static final Map<String, PackageScanner> PACKAGE_SCANNER_CONTEXT = new HashMap<>();
I'd rename it, the name is not clear for me

2021-10-30 10:46 UTC, MrFim commented on src/main/java/com/bring/library/service/processor/impl/PackageScanner.java
> +    private Map<Class, Object> instanceOfClasses = new HashMap<>();
1. final
2. using row classes makes a lot of warning
3. rename it according to patterns: `keyToValue` or `valueByKey`

2021-10-30 10:47 UTC, MrFim commented on src/main/java/com/bring/library/service/processor/impl/PackageScanner.java
> +    private List<Class> classes = new ArrayList<>();
final

2021-10-30 10:49 UTC, MrFim commented on src/main/java/com/bring/library/service/processor/impl/PackageScanner.java
> +            classes.addAll(getClassesByPackageName(mainPackageName));
I would extract logic from constructor to a separate method

2021-10-30 10:49 UTC, MrFim commented on src/main/java/com/bring/library/service/processor/impl/PackageScanner.java
> +    public PackageScanner(String mainPackageName) {
add checking for null

2021-10-30 10:50 UTC, MrFim commented on src/main/java/com/bring/library/service/processor/impl/PackageScanner.java
> +            throw new EmptyDirectoryException("Can't get information about all classes", e);
EmptyDirectoryException is not the right name, it should be more general

2021-10-30 10:50 UTC, MrFim commented on src/main/java/com/bring/library/service/processor/impl/PackageScanner.java
> +    public static PackageScanner scanPackage(String mainPackageName) {
why static?

2021-10-30 10:54 UTC, MrFim commented on src/main/java/com/bring/library/service/processor/impl/PackageScanner.java
> +        PackageScanner packageScanner = new PackageScanner(mainPackageName);
for me it seems strange, you call static method and inside you create an instance of this class. I would create an instance at first

2021-10-30 11:02 UTC, MrFim commented on src/main/java/com/bring/library/service/processor/impl/PackageScanner.java
> +    public Object getBean(Class certainInterface) {
1. if I pass direct class it will fail, am I right?
2. We want to be able to get by name too
3. IMO this is out of scope of your task
4. not bean, but bobo maybe
5. need to change logic if we have 2 classes that implements one interface

2021-10-30 11:03 UTC, MrFim commented on src/main/java/com/bring/library/service/processor/impl/PackageScanner.java
> +    private Class<?> findClassExtendingInterface(Class<?> certainInterface) {
IMO out of scope of your task, we have `BoboCreatorService`

2021-10-30 11:04 UTC, MrFim commented on src/main/java/com/bring/library/service/processor/impl/PackageScanner.java
> +    private Object getNewInstance(Class<?> certainClass) {
out of scope

2021-10-30 11:05 UTC, MrFim commented on src/main/java/com/bring/library/service/processor/impl/PackageScanner.java
> +            Object newInstance = constructorDao.newInstance();
point for the future: it seems like it work only for empty consturctor

2021-10-30 11:05 UTC, MrFim commented on src/main/java/com/bring/library/service/processor/impl/PackageScanner.java
> +    public Object getBean(Class certainInterface) {
I think for public methods we need documentation

2021-10-30 11:07 UTC, MrFim commented on src/main/java/com/bring/library/service/processor/impl/PackageScanner.java
> +    private static List<Class> getClassesByPackageName(String packageName) throws IOException, ClassNotFoundException {
it strange for me, you don't have doc for public method, but have for private

2021-10-30 11:10 UTC, MrFim commented on src/main/java/com/bring/library/service/processor/impl/PackageScanner.java
> +     * @throws IOException            if I/O errors occur
for me private methods is a good place to handle exceptions

2021-10-30 11:12 UTC, MrFim commented on src/main/java/com/bring/library/service/processor/impl/PackageScanner.java
> +     * @param packageName The base package
param and return seem almost the same as variable name

2021-10-30 11:13 UTC, MrFim commented on src/main/java/com/bring/library/service/processor/impl/PackageScanner.java
> +        Enumeration<URL> classLoaderResources = classLoader.getResources(path);
why Enumeration?

2021-10-30 11:14 UTC, MrFim commented on src/main/java/com/bring/library/service/processor/impl/PackageScanner.java
> +        String path = packageName.replace(".", "/");
extract in constants

2021-10-30 11:15 UTC, MrFim commented on src/main/java/com/bring/library/service/processor/impl/PackageScanner.java
> +            throw new EmptyClassLoaderException("ClassLoader is null");
it makes me disappointed, exception name says that loader is empty, but message tells that it is null

2021-10-30 11:16 UTC, MrFim commented on src/main/java/com/bring/library/service/processor/impl/PackageScanner.java
> +        classLoaderResources.asIterator().forEachRemaining(resource -> dirs.add(new File(resource.getFile())));
resource -> url?

2021-10-30 11:17 UTC, MrFim commented on src/main/java/com/bring/library/service/processor/impl/PackageScanner.java
> +            classes.addAll(findClasses(directory, packageName));
I don't like when you pass to a method parameter another method, For me it is more readable to extract `findClasses(directory, packageName) `in a variable and pass it

2021-10-30 11:18 UTC, MrFim commented on src/main/java/com/bring/library/service/processor/impl/PackageScanner.java
> +
delete blank line

2021-10-30 11:19 UTC, MrFim commented on src/main/java/com/bring/library/service/processor/impl/PackageScanner.java
> +                    if (fileName.contains(".")) {
how can I reproduce dot in a filename?

2021-10-30 11:24 UTC, MrFim commented on src/main/java/com/bring/library/service/processor/impl/PackageScanner.java
> +                    classes.add(Class.forName(packageName + "." + fileName.substring(0, fileName.length() - 6)));
1. I got an exception here when I pass `""` in packageName, but I think this case is valid. It means that I want to scan root. And problem in logic, I used packageName.substring(1)` and it works fine`
2. Without deep investigation I can't come up why `-6`

2021-10-30 11:25 UTC, MrFim commented on src/main/java/demonstration/project/MainApp.java
> +package demonstration.project;
this example you can add in App class

2021-10-30 11:26 UTC, MrFim commented
Write tests

2021-10-30 11:28 UTC, MrFim requested changes
Fix your code according to my comments, please

2021-10-30 11:30 UTC, MrFim commented on src/main/java/demonstration/project/dao/impl/DaoClass.java
> +public class DaoClass implements DaoInterface {
Use pattern please: InterfaceNameImpl for implementation. For me this approach is not very good, but I think we will follow it

2021-10-30 11:40 UTC, MrFim commented
Want to add that you have 4 point in description for your task. Did you answer all of them?

2021-10-30 11:43 UTC, MrFim commented on src/main/java/demonstration/project/MainApp.java
> +        var context = PackageScanner.scanPackage("demonstration.project");
context should be in Registry. It meant that this is also our of scope of your task

2021-10-30 11:44 UTC, MrFim commented on src/main/java/com/bring/library/service/processor/impl/PackageScanner.java
> +                        throw new InvalidFileNameException("File name shouldn't consist point \".\"");
not point, but dot

2021-10-30 11:50 UTC, MrFim commented on src/main/java/com/bring/library/service/processor/impl/PackageScanner.java
> +    private void setValueToField(Field field, Object instanceOfClass, Object classToInject) {
1. `instanceOfClass ` -> `classInstance`
2. `classToInject ` -> `value`

2021-10-30 12:02 UTC, MrFim commented on src/main/java/com/bring/library/service/processor/impl/PackageScanner.java
> +                Object classToInject = getBean(field.getType());
I have some doubts about this method logic. For me you should take an instance form context

2021-11-02 21:41 UTC, MishaBeheka commented on src/main/java/com/bring/library/service/processor/impl/PackageScanner.java
> +    public static PackageScanner scanPackage(String mainPackageName) {
This is the raw solution made solely for the convenience of demonstration

2021-11-02 21:43 UTC, MishaBeheka commented on src/main/java/com/bring/library/service/processor/impl/PackageScanner.java
> +            Object newInstance = constructorDao.newInstance();
This is the raw solution made solely for the convenience of demonstration

2021-11-02 21:45 UTC, MishaBeheka commented on src/main/java/com/bring/library/service/processor/impl/PackageScanner.java
> +    private static List<Class> getClassesByPackageName(String packageName) throws IOException, ClassNotFoundException {
This is the raw solution made solely for the convenience of demonstration.
I think we will soon move away from static.

2021-11-02 21:46 UTC, MishaBeheka commented on src/main/java/com/bring/library/service/processor/impl/PackageScanner.java
> +        Enumeration<URL> classLoaderResources = classLoader.getResources(path);
Why not?)

2021-11-02 21:53 UTC, MishaBeheka commented on src/main/java/com/bring/library/service/processor/impl/PackageScanner.java
> +        classLoaderResources.asIterator().forEachRemaining(resource -> dirs.add(new File(resource.getFile())));
yes

2021-11-03 13:21 UTC, MrFim reviewed
this pr blocks

2021-11-05 09:56 UTC, merged