Br 29 value injection from property
DimaYakovenko/breskul-bring-project pull request #34
Opened 2021-11-08 17:15 UTC by MishaBeheka

Implemented value injection from file properties

2021-11-09 11:22 UTC, aquariusmaster requested changes
In addition could you please add a section to the README about using this annotation?

2021-11-09 11:22 UTC, aquariusmaster commented on src/test/java/com/bringframework/BoboFactoryTest.java
> +        BoboFactory boboFactory = new BoboFactory(definitions, List.of(new InjectAnnotationBoboConfigurator(), new PropertyValueAnnotationBoboConfigurator()));
Not necessary to add BoboConfigurator here for that test

2021-11-09 11:22 UTC, aquariusmaster commented on src/test/java/com/bringframework/BoboFactoryTest.java
> +        fields.forEach(field -> System.out.println(field.getName()));
you can add assertion instead of printing

2021-11-09 11:22 UTC, aquariusmaster commented on src/test/java/com/bringframework/BoboFactoryTest.java
> +        Field stringField = myService.getClass().getDeclaredField("stringValue");
Maybe it's better to add a getter for `stringValue` in MyServiceImpl instead of using Reflection?

2021-11-09 11:22 UTC, aquariusmaster commented on src/test/java/demonstration/project/service/impl/MyServiceImpl.java
> +//        System.out.println("Value: " + value);
Please remove this line

2021-11-09 11:22 UTC, aquariusmaster commented on src/main/java/com/bringframework/configurator/PropertyValueAnnotationBoboConfigurator.java
> +public class PropertyValueAnnotationBoboConfigurator implements BoboConfigurator {
Please add tests for that class

2021-11-09 18:19 UTC, DimaYakovenko commented on src/main/java/com/bringframework/configurator/PropertyValueAnnotationBoboConfigurator.java
> +public class PropertyValueAnnotationBoboConfigurator implements BoboConfigurator {
Pls rename class to BoboValueAnnotationBoboConfiguration

2021-11-09 19:12 UTC, DimaYakovenko commented on src/main/java/com/bringframework/util/TypeParserUtil.java
> +        String strValue = (String) value;
pls rename strValue -> propertyValue

2021-11-09 19:12 UTC, DimaYakovenko commented on src/test/java/com/bringframework/BoboFactoryTest.java
> +    public void findAllFieldsWithAnnotationBoboValue() {
Pls extract all your test cases to a separate test class, because they are not connected directly with BoboFactory

2021-11-09 19:52 UTC, MishaBeheka commented on src/main/java/com/bringframework/annotation/BoboValue.java
> +@Target({ElementType.FIELD, ElementType.METHOD, ElementType.PARAMETER})
It is for the future. I think it will be useful soon. It can be the next task.

2021-11-09 19:58 UTC, MishaBeheka commented on src/main/java/com/bringframework/configurator/PropertyValueAnnotationBoboConfigurator.java
> +                Object value = annotation.value().isEmpty() ? propertiesMap.get(field.getName()) : propertiesMap.get(annotation.value());
Yes, but it can change to another type.

2021-11-09 19:58 UTC, MishaBeheka commented on src/main/java/com/bringframework/configurator/PropertyValueAnnotationBoboConfigurator.java
> +                value = TypeParserUtil.parseToType(value, field.getType());
Yes, but it can change to another type.

2021-11-09 20:06 UTC, MishaBeheka commented on src/main/java/com/bringframework/util/TypeParserUtil.java
> +    public static Object parseToType(Object value, Class<?> clazz) {
Yes, but I wouldn't like to do another variable for the value in PropertyValueAnnotationBoboConfigurator class.

2021-11-09 20:06 UTC, MishaBeheka commented on src/main/java/com/bringframework/util/TypeParserUtil.java
> +    public static Object parseToType(Object value, Class<?> clazz) {
And since this is the util class, it can be used elsewhere. Therefore, in my opinion, it should be more universal.

2021-11-10 07:04 UTC, DimaYakovenko commented on src/main/java/com/bringframework/configurator/PropertyValueAnnotationBoboConfigurator.java
> +        propertiesMap = lines.map(line -> line.split("=")).collect(toMap(arr -> arr[0], arr -> arr[1]));
pls rename arr -> keyValue

2021-11-10 14:42 UTC, MishaBeheka commented on src/main/java/com/bringframework/configurator/PropertyValueAnnotationBoboConfigurator.java
> +        propertiesMap = lines.map(line -> line.split("=")).collect(toMap(arr -> arr[0], arr -> arr[1]));
Done

2021-11-10 14:45 UTC, MishaBeheka commented on src/test/java/com/bringframework/BoboFactoryTest.java
> +        BoboFactory boboFactory = new BoboFactory(definitions, List.of(new InjectAnnotationBoboConfigurator(), new PropertyValueAnnotationBoboConfigurator()));
Done

2021-11-10 14:46 UTC, MishaBeheka commented on src/test/java/com/bringframework/BoboFactoryTest.java
> +        fields.forEach(field -> System.out.println(field.getName()));
It was for me. I deleted it.

2021-11-10 14:52 UTC, MishaBeheka commented on src/main/java/com/bringframework/configurator/PropertyValueAnnotationBoboConfigurator.java
> +public class PropertyValueAnnotationBoboConfigurator implements BoboConfigurator {
Done

2021-11-10 14:52 UTC, MishaBeheka commented on src/main/java/com/bringframework/util/TypeParserUtil.java
> +public final class TypeParserUtil {
Done

2021-11-10 14:52 UTC, MishaBeheka commented on src/main/java/com/bringframework/util/TypeParserUtil.java
> +        String strValue = (String) value;
Done

2021-11-10 14:53 UTC, MishaBeheka commented on src/test/java/com/bringframework/BoboFactoryTest.java
> +    public void findAllFieldsWithAnnotationBoboValue() {
Done

2021-11-10 16:43 UTC, MishaBeheka commented on src/test/java/com/bringframework/BoboFactoryTest.java
> +        Field stringField = myService.getClass().getDeclaredField("stringValue");
Do you suggest to add getters to class by reflection or use annotation @Getter for this class?

2021-11-10 16:43 UTC, MishaBeheka commented on src/test/java/demonstration/project/service/impl/MyServiceImpl.java
> +//        System.out.println("Value: " + value);
Done

2021-11-11 10:15 UTC, MishaBeheka commented on src/main/java/com/bringframework/configurator/PropertyValueAnnotationBoboConfigurator.java
> +    @SneakyThrows
Done

2021-11-11 10:16 UTC, MishaBeheka commented on src/main/java/com/bringframework/configurator/PropertyValueAnnotationBoboConfigurator.java
> +    @SneakyThrows
Done

2021-11-11 10:16 UTC, MishaBeheka commented on src/main/java/com/bringframework/util/TypeParserUtil.java
> +        return value;
I am not shure

2021-11-11 10:17 UTC, MishaBeheka commented on src/main/resources/application.properties
> +some.string.value=value
Done

2021-11-11 10:18 UTC, MishaBeheka commented on src/test/java/com/bringframework/BoboFactoryTest.java
> +        Field stringField = myService.getClass().getDeclaredField("stringValue");
Done

2021-11-11 11:01 UTC, DimaYakovenko commented
Pls add javadoc to the interfaces and public methods

2021-11-11 14:03 UTC, MishaBeheka commented on src/main/java/com/bringframework/annotation/BoboValue.java
> +@Target({ElementType.FIELD, ElementType.METHOD, ElementType.PARAMETER})
Done

2021-11-11 14:04 UTC, MishaBeheka commented on src/main/java/com/bringframework/configurator/BoboValueAnnotationConfiguration.java
> +    private final String LINE_SPLIT_REGEX = "=";
Done

2021-11-11 14:04 UTC, MishaBeheka commented on src/main/java/com/bringframework/configurator/BoboValueAnnotationConfiguration.java
> +    private Stream<String> findAvailableProperties() {
Done

2021-11-12 16:51 UTC, MrFim commented on README.md
> +`@BoboValue` annotation allows you to get values from a properties file.
from a `.`properties file.

2021-11-12 18:16 UTC, aquariusmaster commented on src/main/java/com/bringframework/configurator/BoboValueAnnotationConfiguration.java
> +    }
How about this way?
```
        if (path == null) {
            return Collections.emptyList();
        }
        return readPropertiesByPath(path).collect(Collectors.toList());
       
```

2021-11-12 18:29 UTC, MrFim commented on src/test/java/com/bringframework/BoboValueAnnotationConfigurationTest.java
> +class BoboValueAnnotationConfigurationTest {
please, add test for case, when we write wrong value to @ Value which is not in application.properties

2021-11-13 08:21 UTC, MishaBeheka commented on README.md
> +`@BoboValue` annotation allows you to get values from a properties file.
I don't understand what you mean. Explain pls.

2021-11-13 08:34 UTC, MishaBeheka commented on src/main/java/com/bringframework/configurator/BoboValueAnnotationConfiguration.java
> +    }
Done

2021-11-14 09:26 UTC, MishaBeheka commented on src/main/java/com/bringframework/configurator/BoboValueAnnotationConfiguration.java
> +        String path = ClassLoader.getSystemClassLoader().getResource("application.properties").getPath();
Done

2021-11-14 09:26 UTC, MishaBeheka commented on src/main/java/com/bringframework/configurator/BoboValueAnnotationConfiguration.java
> +                Object value = annotation.value().isEmpty()
Done

2021-11-14 09:26 UTC, MishaBeheka commented on src/main/java/com/bringframework/configurator/BoboValueAnnotationConfiguration.java
> +    }
Changed

2021-11-14 09:27 UTC, MishaBeheka commented on README.md
> +`@BoboValue` annotation allows you to get values from a properties file.
What do you mean? Explain pls.

2021-11-14 09:30 UTC, MishaBeheka commented on src/main/java/com/bringframework/configurator/BoboValueAnnotationConfiguration.java
> +            return new BufferedReader(new FileReader(path)).lines();
My mistake) You're right! Fixed!)

2021-11-14 09:30 UTC, MishaBeheka commented on src/main/java/com/bringframework/util/TypeResolverUtil.java
> +        if (!(value instanceof String)) return value;
Changed

2021-11-14 09:32 UTC, MishaBeheka commented on src/test/java/com/bringframework/BoboValueAnnotationConfigurationTest.java
> +    private final String TEST_DEMONSTRATION_PACKAGE_PATH = "demonstration.project";
Done

2021-11-15 10:19 UTC, aquariusmaster commented on src/main/java/com/bringframework/configurator/BoboValueAnnotationConfiguration.java
> +            if (field.isAnnotationPresent(BoboValue.class)) {
How about checking whether this annotated field has a number or string type? And if the field is not a number or string then we can throw an exception. 
Can you check similar logic in Spring?

2021-11-16 14:42 UTC, aquariusmaster commented on src/main/java/com/bringframework/configurator/BoboValueAnnotationConfiguration.java
> +            if (field.isAnnotationPresent(BoboValue.class)) {
Already covered

2021-11-25 16:17 UTC, aquariusmaster commented on src/test/java/com/bringframework/configurator/BoboValueAnnotationConfigurationTest.java
> +        modifiers.setInt(field, field.getModifiers() & ~Modifier.FINAL);
Wow, interesting what is that?

2021-11-25 16:35 UTC, aquariusmaster commented on src/main/java/com/bringframework/util/TypeResolverUtil.java
> +public final class TypeResolverUtil {
Test?

2021-11-25 16:35 UTC, aquariusmaster commented on src/test/java/com/bringframework/configurator/BoboValueAnnotationConfigurationTest.java
> +    void whenApplicationPropertiesFileExists_andHasProperties() {
I guess the name could be `whenApplicationPropertiesFileExistsAndHasProperties_thenFillPropertyMaps`

2021-11-25 16:35 UTC, aquariusmaster commented on src/test/resources/application.properties
> +defaultValue=DefaultValue
Have your tests covered the case where the key is defined but the value is not?
`port=`

2021-11-25 17:41 UTC, MishaBeheka commented on src/test/java/com/bringframework/configurator/BoboValueAnnotationConfigurationTest.java
> +        modifiers.setInt(field, field.getModifiers() & ~Modifier.FINAL);
It is my experiment. I forgot to remove this method.

2021-11-25 17:47 UTC, MishaBeheka commented on src/test/java/com/bringframework/configurator/BoboValueAnnotationConfigurationTest.java
> +    void whenApplicationPropertiesFileExists_andHasProperties() {
Ok

2021-11-25 17:47 UTC, MishaBeheka commented on src/test/resources/application.properties
> +defaultValue=DefaultValue
Now yes)

2021-11-25 17:49 UTC, MishaBeheka commented on src/main/java/com/bringframework/util/TypeResolverUtil.java
> +public final class TypeResolverUtil {
Do you think that need tests for this class?

2021-11-25 20:08 UTC, aquariusmaster commented on src/main/java/com/bringframework/util/TypeResolverUtil.java
> +public final class TypeResolverUtil {
I believe we should have tests (for prod for sure)
We write tests to cover all logic we write to be sure we won't break something when we change code.

2021-11-25 20:10 UTC, aquariusmaster approved these changes

2021-11-26 09:39 UTC, DimaYakovenko approved these changes

2021-11-26 09:55 UTC, MishaBeheka commented on src/test/java/com/bringframework/BoboValueAnnotationConfigurationTest.java
> +class BoboValueAnnotationConfigurationTest {
Done

2021-11-29 14:38 UTC, merged