BR-16 Add processing for Bobo and Configuration annotations
DimaYakovenko/breskul-bring-project pull request #37
Opened 2021-11-13 22:14 UTC by MrFim

2021-11-13 23:10 UTC, DimaYakovenko commented on src/main/java/com/bringframework/configurator/BoboAnnotationConfigurator.java
> +    public void configure(Object bobo, BoboRegistry registry) {
minor: I would rename bobo to smth like configBobo

2021-11-13 23:10 UTC, DimaYakovenko commented on src/main/java/com/bringframework/configurator/BoboAnnotationConfigurator.java
> +    private void registerBobo(Object bobo, BoboRegistry registry, Method method) {
and here as well, bobo -> configBobo. for me it was difficult to keep in mind which one is configuration class bobo and which is created from method annotated with @ bobo.

2021-11-14 09:58 UTC, aquariusmaster requested changes

2021-12-07 09:57 UTC, aquariusmaster commented on src/main/java/com/bringframework/BoboFactory.java
> +        Object config = configClassType.getDeclaredConstructor().newInstance();
Here you create Configuration object each time you create Bobo object. I think to avoid this we can make Configuration also as Bobo (bean) too.
And then call registry for the Configuration object:
```
Object config = registry.getBobo(definition.getConfigurationBoboName());
configClassType.getMethod(definition.getConfigurationMethodName()).invoke(config);
```

2021-12-07 14:55 UTC, DimaYakovenko commented on src/main/java/com/bringframework/exception/ExceptionErrorMessage.java
> +    public static final String NO_SUCH_BOBO_DEFINIITON_EXCEPTION_BY_NAME = "No such bobo definition with name '%s'";
here is a small typo in `DEFINIITON` 
and I would rename them to
`NO_SUCH_BOBO_DEFINITION_BY_TYPE_EXCEPTION`
`NO_SUCH_BOBO_DEFINITION_BY_NAME_EXCEPTION`
that _EXCEPTION would be at the end

2021-12-07 15:12 UTC, DimaYakovenko approved these changes

2021-12-08 19:46 UTC, aquariusmaster approved these changes

2021-12-08 19:49 UTC, merged